### ISSUE TITLE
How to run HL7 Listener on Linux Server

### ISSUE THREAD

**Issue by hekler91** [RobHolme/HL7-Listener#4]
Hello

First of all, thank you for the HL7 Listener. It works great on Windows.
I am now trying to run Hl7 Listener on Linux Server.

I use:

Alpine Linux v3.16

and I did the first item:
1.) Install the .Net 6.0 SDK for Linux

this is what the installation currently looks like:
![image](https://user-images.githubusercontent.com/42637708/205074934-a04c76e8-c6a1-46dd-807c-80be2b108ef1.png)

can you please help me, how can I run this script now with linux, and is it even possible?

Thanks a lot for your reply.

**Comment by hekler91** [comment]
I find a solution:  ./HL7Listener -Port 5000 -FilePath /opt/HL7Outgoing -Encoding Latin1

**Comment by RobHolme** [comment]
The Readme contains instructions on how to run the application:  https://github.com/RobHolme/HL7-Listener/blob/master/README.md#running-hl7listener

If you wanted to avoid installing the .NET SDK to build the application, pre-built releases are available from: https://github.com/RobHolme/HL7-Listener/releases 

These are self-contained releases that include the relevant .Net dependencies, it does not require the .Net runtime to be installed.
